name = "Security-Key"
main = "app/main.py" # Onde está o seu app FastAPI
compatibility_date = "2025-01-02"

[vars]
# Aqui você pode colocar variáveis que não são secretas
APP_NAME="Security Key"
APP_VERSION="1.0.0"
DEBUG="False"
ALGORITHM="HS256"
ACCESS_TOKEN_EXPIRE_MINUTES=30

# Se o seu projeto usa compatibilidade com Python
[[python_workers]]
handler = "app" # O nome da variável FastAPI no seu código (ex: app = FastAPI())